// This header is generated by cbindgen. Do not edit manually.
// Regenerate with: cbindgen --config rust/libnfc-rs/cbindgen.toml --crate libnfc-rs --output rust/libnfc-rs/include/libnfc_rs.h

#ifndef LIBNFC_RS_H
#define LIBNFC_RS_H

#pragma once

/* Generated with cbindgen:0.29.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

extern void log_put_message(uint8_t group,
                            const char *category,
                            uint8_t priority,
                            const char *message);

int nfc_parse_connstring(const char *connstring,
                         const char *prefix,
                         const char *param_name,
                         char *param_value,
                         size_t param_value_size);

int nfc_build_connstring(char *dest,
                         size_t dest_size,
                         const char *driver_name,
                         const char *param_name,
                         const char *param_value);

int nfc_safe_memcpy(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_safe_memmove(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_secure_memset(void *ptr, int val, size_t size);

/* Debug helpers (feature-gated) are not exported in the stable header.
     To regenerate a header including debug helpers (for local testing),
     run cbindgen in a Rust build that enables the debug feature. For
     example, from the repository root run:

         cargo build -p libnfc-rs --features "nfc_secure nfc_secure_debug"
         cbindgen --config rust/libnfc-rs/cbindgen.toml --crate libnfc-rs --output build/rust-target/include/libnfc_rs_debug.h

     The stable tracked header intentionally excludes debug-only helpers
     such as buffer-overlap checks and suspicious-size warnings.

int nfc_is_null_terminated(const char *buf, size_t bufsize);

void nfc_ensure_null_terminated(char *buf, size_t bufsize);

const char *nfc_get_last_error(void);

void nfc_clear_last_error(void);

void nfc_set_last_error(const char *message);

int connstring_decode(const char *connstring,
                      const char *driver_name,
                      const char *bus_name,
                      char **pparam1,
                      char **pparam2);

/* Free memory allocated by Rust FFI helpers */
void nfc_rs_free(void *ptr);

#endif /* LIBNFC_RS_H */

/* End of generated header */
