// This header is generated by cbindgen. Do not edit manually.
// Repo-local private header; not installed.
// Regenerate with: python3 rust/proximate-sys/tools/generate_cbindgen_header.py --config rust/proximate-sys/cbindgen.private.toml --output rust/proximate-sys/include/libnfc_rs_private.h

// Manually-provided macros for values that cbindgen cannot emit
#define LOG_CATEGORY "libnfc.common"
#define MALLOC_LABEL "malloc"
#define NFC_BUFSIZE_CONNSTRING 1024
#define NFC_SUCCESS 0
#define NFC_EIO -1
#define NFC_EINVARG -2
#define NFC_EDEVNOTSUPP -3
#define NFC_ENOTSUCHDEV -4
#define NFC_EOVFLOW -5
#define NFC_ETIMEOUT -6
#define NFC_EOPABORTED -7
#define NFC_ENOTIMPL -8
#define NFC_ETGRELEASED -10
#define NFC_ERFTRANS -20
#define NFC_EMFCAUTHFAIL -30
#define NFC_ESOFT -80
#define NFC_ECHIP -90
#define NFC_COMMON_SUCCESS 0
#define NFC_COMMON_ERROR -1
#define LOG_GROUP_GENERAL 1
#define LOG_PRIORITY_ERROR 1
#define LOG_PRIORITY_DEBUG 3
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#else
#include <sys/types.h>
#endif

void nfc_rs_log_message(unsigned char group, const char *category, unsigned char priority, const char *message);


#ifndef LIBNFC_RS_PRIVATE_H
#define LIBNFC_RS_PRIVATE_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define DEVICE_NAME_LENGTH 256

#define MAX_USER_DEFINED_DEVICES 4

#define NFC_DRIVER_NAME_MAX 64

#define Diagnose 0

#define PN53x_EXTENDED_FRAME__DATA_MAX_LEN 264

#define PN53x_ACK_FRAME__LEN 6

#define PN53X_REG_CIU_TxMode 25346

typedef enum scan_type_enum {
  NOT_INTRUSIVE = 0,
  INTRUSIVE = 1,
  NOT_AVAILABLE = 2,
} scan_type_enum;

typedef enum nfc_dep_mode {
  NDM_UNDEFINED = 0,
  NDM_PASSIVE = 1,
  NDM_ACTIVE = 2,
} nfc_dep_mode;

typedef enum nfc_baud_rate {
  NBR_UNDEFINED = 0,
  NBR_106 = 1,
  NBR_212 = 2,
  NBR_424 = 3,
  NBR_847 = 4,
} nfc_baud_rate;

typedef enum nfc_property {
  NP_TIMEOUT_COMMAND = 0,
  NP_TIMEOUT_ATR = 1,
  NP_TIMEOUT_COM = 2,
  NP_HANDLE_CRC = 3,
  NP_HANDLE_PARITY = 4,
  NP_ACTIVATE_FIELD = 5,
  NP_ACTIVATE_CRYPTO1 = 6,
  NP_INFINITE_SELECT = 7,
  NP_ACCEPT_INVALID_FRAMES = 8,
  NP_ACCEPT_MULTIPLE_FRAMES = 9,
  NP_AUTO_ISO14443_4 = 10,
  NP_EASY_FRAMING = 11,
  NP_FORCE_ISO14443_A = 12,
  NP_FORCE_ISO14443_B = 13,
  NP_FORCE_SPEED_106 = 14,
} nfc_property;

typedef enum nfc_mode {
  N_TARGET = 0,
  N_INITIATOR = 1,
} nfc_mode;

typedef enum nfc_modulation_type {
  NMT_UNDEFINED = 0,
  NMT_ISO14443A = 1,
  NMT_JEWEL = 2,
  NMT_ISO14443B = 3,
  NMT_ISO14443BI = 4,
  NMT_ISO14443B2SR = 5,
  NMT_ISO14443B2CT = 6,
  NMT_FELICA = 7,
  NMT_DEP = 8,
  NMT_BARCODE = 9,
  NMT_ISO14443BICLASS = 10,
} nfc_modulation_type;

typedef enum pn532_sam_mode {
  PSM_NORMAL = 1,
  PSM_VIRTUAL_CARD = 2,
  PSM_WIRED_CARD = 3,
  PSM_DUAL_CARD = 4,
} pn532_sam_mode;

#pragma pack(push, 1)

typedef struct nfc_barcode_info {
  size_t szDataLen;
  uint8_t abtData[32];
} nfc_barcode_info;

typedef struct nfc_dep_info {
  uint8_t abtNFCID3[10];
  uint8_t btDID;
  uint8_t btBS;
  uint8_t btBR;
  uint8_t btTO;
  uint8_t btPP;
  uint8_t abtGB[48];
  size_t szGB;
  nfc_dep_mode ndm;
} nfc_dep_info;

typedef struct nfc_felica_info {
  size_t szLen;
  uint8_t btResCode;
  uint8_t abtId[8];
  uint8_t abtPad[8];
  uint8_t abtSysCode[2];
} nfc_felica_info;

typedef struct nfc_iso14443a_info {
  uint8_t abtAtqa[2];
  uint8_t btSak;
  size_t szUidLen;
  uint8_t abtUid[10];
  size_t szAtsLen;
  uint8_t abtAts[254];
} nfc_iso14443a_info;

typedef struct nfc_iso14443b2ct_info {
  uint8_t abtUID[4];
  uint8_t btProdCode;
  uint8_t btFabCode;
} nfc_iso14443b2ct_info;

typedef struct nfc_iso14443b2sr_info {
  uint8_t abtUID[8];
} nfc_iso14443b2sr_info;

typedef struct nfc_iso14443b_info {
  uint8_t abtPupi[4];
  uint8_t abtApplicationData[4];
  uint8_t abtProtocolInfo[3];
  uint8_t ui8CardIdentifier;
} nfc_iso14443b_info;

typedef struct nfc_iso14443bi_info {
  uint8_t abtDIV[4];
  uint8_t btVerLog;
  uint8_t btConfig;
  size_t szAtrLen;
  uint8_t abtAtr[33];
} nfc_iso14443bi_info;

typedef struct nfc_iso14443biclass_info {
  uint8_t abtUID[8];
} nfc_iso14443biclass_info;

typedef struct nfc_jewel_info {
  uint8_t btSensRes[2];
  uint8_t btId[4];
} nfc_jewel_info;

typedef struct nfc_modulation {
  nfc_modulation_type nmt;
  nfc_baud_rate nbr;
} nfc_modulation;

typedef union nfc_target_info {
  nfc_iso14443a_info nai;
  nfc_felica_info nfi;
  nfc_iso14443b_info nbi;
  nfc_iso14443bi_info nii;
  nfc_iso14443b2sr_info nsi;
  nfc_iso14443b2ct_info nci;
  nfc_jewel_info nji;
  nfc_dep_info ndi;
  nfc_barcode_info nti;
  nfc_iso14443biclass_info nhi;
} nfc_target_info;

typedef struct nfc_target {
  nfc_target_info nti;
  nfc_modulation nm;
} nfc_target;

#pragma pack(pop)


typedef struct nfc_user_defined_device {
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool optional;
} nfc_user_defined_device;

typedef struct nfc_context {
  bool allow_autoscan;
  bool allow_intrusive_scan;
  uint32_t log_level;
  struct nfc_user_defined_device user_defined_devices[MAX_USER_DEFINED_DEVICES];
  unsigned int user_defined_device_count;
} nfc_context;

typedef char nfc_connstring[NFC_BUFSIZE_CONNSTRING];

typedef uintptr_t (*nfc_driver_scan_fn)(const struct nfc_context*, nfc_connstring*, uintptr_t);

typedef struct nfc_device *(*nfc_driver_open_fn)(const struct nfc_context*, const char*);

typedef void (*nfc_driver_close_fn)(struct nfc_device*);

typedef const char *(*nfc_driver_strerror_fn)(const struct nfc_device*);

typedef int (*nfc_driver_initiator_init_fn)(struct nfc_device*);

typedef int (*nfc_driver_initiator_init_secure_element_fn)(struct nfc_device*);

typedef int (*nfc_driver_initiator_select_passive_target_fn)(struct nfc_device*,
                                                             struct nfc_modulation,
                                                             const uint8_t*,
                                                             uintptr_t,
                                                             struct nfc_target*);

typedef int (*nfc_driver_initiator_poll_target_fn)(struct nfc_device*,
                                                   const struct nfc_modulation*,
                                                   uintptr_t,
                                                   uint8_t,
                                                   uint8_t,
                                                   struct nfc_target*);

typedef int (*nfc_driver_initiator_select_dep_target_fn)(struct nfc_device*,
                                                         enum nfc_dep_mode,
                                                         enum nfc_baud_rate,
                                                         const struct nfc_dep_info*,
                                                         struct nfc_target*,
                                                         int);

typedef int (*nfc_driver_initiator_deselect_target_fn)(struct nfc_device*);

typedef int (*nfc_driver_initiator_transceive_bytes_fn)(struct nfc_device*,
                                                        const uint8_t*,
                                                        uintptr_t,
                                                        uint8_t*,
                                                        uintptr_t,
                                                        int);

typedef int (*nfc_driver_initiator_transceive_bits_fn)(struct nfc_device*,
                                                       const uint8_t*,
                                                       uintptr_t,
                                                       const uint8_t*,
                                                       uint8_t*,
                                                       uint8_t*);

typedef int (*nfc_driver_initiator_transceive_bytes_timed_fn)(struct nfc_device*,
                                                              const uint8_t*,
                                                              uintptr_t,
                                                              uint8_t*,
                                                              uintptr_t,
                                                              uint32_t*);

typedef int (*nfc_driver_initiator_transceive_bits_timed_fn)(struct nfc_device*,
                                                             const uint8_t*,
                                                             uintptr_t,
                                                             const uint8_t*,
                                                             uint8_t*,
                                                             uint8_t*,
                                                             uint32_t*);

typedef int (*nfc_driver_initiator_target_is_present_fn)(struct nfc_device*,
                                                         const struct nfc_target*);

typedef int (*nfc_driver_target_init_fn)(struct nfc_device*,
                                         struct nfc_target*,
                                         uint8_t*,
                                         uintptr_t,
                                         int);

typedef int (*nfc_driver_target_send_bytes_fn)(struct nfc_device*, const uint8_t*, uintptr_t, int);

typedef int (*nfc_driver_target_receive_bytes_fn)(struct nfc_device*, uint8_t*, uintptr_t, int);

typedef int (*nfc_driver_target_send_bits_fn)(struct nfc_device*,
                                              const uint8_t*,
                                              uintptr_t,
                                              const uint8_t*);

typedef int (*nfc_driver_target_receive_bits_fn)(struct nfc_device*, uint8_t*, uintptr_t, uint8_t*);

typedef int (*nfc_driver_device_set_property_bool_fn)(struct nfc_device*, enum nfc_property, bool);

typedef int (*nfc_driver_device_set_property_int_fn)(struct nfc_device*, enum nfc_property, int);

typedef int (*nfc_driver_get_supported_modulation_fn)(struct nfc_device*,
                                                      enum nfc_mode,
                                                      const enum nfc_modulation_type**);

typedef int (*nfc_driver_get_supported_baud_rate_fn)(struct nfc_device*,
                                                     enum nfc_mode,
                                                     enum nfc_modulation_type,
                                                     const enum nfc_baud_rate**);

typedef int (*nfc_driver_device_get_information_about_fn)(struct nfc_device*, char**);

typedef int (*nfc_driver_device_control_fn)(struct nfc_device*);

typedef struct nfc_driver {
  const char *name;
  enum scan_type_enum scan_type;
  nfc_driver_scan_fn scan;
  nfc_driver_open_fn open;
  nfc_driver_close_fn close;
  nfc_driver_strerror_fn strerror;
  nfc_driver_initiator_init_fn initiator_init;
  nfc_driver_initiator_init_secure_element_fn initiator_init_secure_element;
  nfc_driver_initiator_select_passive_target_fn initiator_select_passive_target;
  nfc_driver_initiator_poll_target_fn initiator_poll_target;
  nfc_driver_initiator_select_dep_target_fn initiator_select_dep_target;
  nfc_driver_initiator_deselect_target_fn initiator_deselect_target;
  nfc_driver_initiator_transceive_bytes_fn initiator_transceive_bytes;
  nfc_driver_initiator_transceive_bits_fn initiator_transceive_bits;
  nfc_driver_initiator_transceive_bytes_timed_fn initiator_transceive_bytes_timed;
  nfc_driver_initiator_transceive_bits_timed_fn initiator_transceive_bits_timed;
  nfc_driver_initiator_target_is_present_fn initiator_target_is_present;
  nfc_driver_target_init_fn target_init;
  nfc_driver_target_send_bytes_fn target_send_bytes;
  nfc_driver_target_receive_bytes_fn target_receive_bytes;
  nfc_driver_target_send_bits_fn target_send_bits;
  nfc_driver_target_receive_bits_fn target_receive_bits;
  nfc_driver_device_set_property_bool_fn device_set_property_bool;
  nfc_driver_device_set_property_int_fn device_set_property_int;
  nfc_driver_get_supported_modulation_fn get_supported_modulation;
  nfc_driver_get_supported_baud_rate_fn get_supported_baud_rate;
  nfc_driver_device_get_information_about_fn device_get_information_about;
  nfc_driver_device_control_fn abort_command;
  nfc_driver_device_control_fn idle;
  nfc_driver_device_control_fn powerdown;
} nfc_driver;

typedef struct nfc_device {
  const struct nfc_context *context;
  const struct nfc_driver *driver;
  void *driver_data;
  void *chip_data;
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool bCrc;
  bool bPar;
  bool bEasyFraming;
  bool bInfiniteSelect;
  bool bAutoIso14443_4;
  uint8_t btSupportByte;
  int last_error;
} nfc_device;

typedef int (*pn53x_io_send_fn)(struct nfc_device*, const uint8_t*, uintptr_t, int);

typedef int (*pn53x_io_receive_fn)(struct nfc_device*, uint8_t*, uintptr_t, int);

typedef struct pn53x_io {
  pn53x_io_send_fn send;
  pn53x_io_receive_fn receive;
} pn53x_io;

struct nfc_emulator;

typedef int (*nfc_emulation_io_fn)(struct nfc_emulator *emulator,
                                   const uint8_t *data_in,
                                   size_t data_in_len,
                                   uint8_t *data_out,
                                   size_t data_out_len);

typedef struct nfc_emulation_state_machine {
  nfc_emulation_io_fn io;
  void *data;
} nfc_emulation_state_machine;

typedef struct nfc_emulator {
  struct nfc_target *target;
  struct nfc_emulation_state_machine *state_machine;
  void *user_data;
} nfc_emulator;


void nfc_set_last_error(const char *message);

void nfc_rs_log_message(uint8_t group, const char *category, uint8_t priority, const char *message);

void nfc_rs_free(void *ptr);

struct nfc_context *nfc_context_alloc_defaults(void);

struct nfc_context *nfc_context_new(void);

struct nfc_device *nfc_device_new(const struct nfc_context *context, const char *connstring);

void nfc_device_free(struct nfc_device *device);

void nfc_context_free(struct nfc_context *context);

int nfc_register_driver(const struct nfc_driver *driver);

struct nfc_device *nfc_open(struct nfc_context *context, const char *connstring);

size_t nfc_list_devices(struct nfc_context *context,
                        nfc_connstring *connstrings,
                        size_t connstrings_len);

void nfc_init(struct nfc_context **context);

void nfc_exit(struct nfc_context *context);

void nfc_close(struct nfc_device *device);

void nfc_free(void *ptr);

const char *nfc_version(void);

const char *str_nfc_baud_rate(enum nfc_baud_rate value);

const char *str_nfc_modulation_type(enum nfc_modulation_type value);

int str_nfc_target(char **buf, const struct nfc_target *target, bool verbose);

int nfc_device_set_property_int(struct nfc_device *device, enum nfc_property property, int value);

int nfc_device_set_property_bool(struct nfc_device *device,
                                 enum nfc_property property,
                                 bool enable);

int nfc_initiator_init(struct nfc_device *device);

int nfc_initiator_init_secure_element(struct nfc_device *device);

int nfc_initiator_select_passive_target(struct nfc_device *device,
                                        struct nfc_modulation nm,
                                        const uint8_t *init_data,
                                        size_t init_data_len,
                                        struct nfc_target *target);

int nfc_initiator_list_passive_targets(struct nfc_device *device,
                                       struct nfc_modulation nm,
                                       struct nfc_target *targets,
                                       size_t targets_len);

int nfc_initiator_poll_target(struct nfc_device *device,
                              const struct nfc_modulation *modulation_types,
                              size_t modulation_types_len,
                              uint8_t poll_nr,
                              uint8_t period,
                              struct nfc_target *target);

int nfc_initiator_select_dep_target(struct nfc_device *device,
                                    enum nfc_dep_mode dep_mode,
                                    enum nfc_baud_rate baud_rate,
                                    const struct nfc_dep_info *initiator,
                                    struct nfc_target *target,
                                    int timeout);

int nfc_initiator_poll_dep_target(struct nfc_device *device,
                                  enum nfc_dep_mode dep_mode,
                                  enum nfc_baud_rate baud_rate,
                                  const struct nfc_dep_info *initiator,
                                  struct nfc_target *target,
                                  int timeout);

int nfc_initiator_deselect_target(struct nfc_device *device);

int nfc_initiator_target_is_present(struct nfc_device *device, const struct nfc_target *target);

int nfc_target_init(struct nfc_device *device,
                    struct nfc_target *target,
                    uint8_t *rx,
                    size_t rx_len,
                    int timeout);

int nfc_initiator_transceive_bytes(struct nfc_device *device,
                                   const uint8_t *tx,
                                   size_t tx_len,
                                   uint8_t *rx,
                                   size_t rx_len,
                                   int timeout);

int nfc_initiator_transceive_bits(struct nfc_device *device,
                                  const uint8_t *tx,
                                  size_t tx_bits_len,
                                  const uint8_t *tx_parity,
                                  uint8_t *rx,
                                  size_t rx_len,
                                  uint8_t *rx_parity);

int nfc_initiator_transceive_bytes_timed(struct nfc_device *device,
                                         const uint8_t *tx,
                                         size_t tx_len,
                                         uint8_t *rx,
                                         size_t rx_len,
                                         uint32_t *cycles);

int nfc_initiator_transceive_bits_timed(struct nfc_device *device,
                                        const uint8_t *tx,
                                        size_t tx_bits_len,
                                        const uint8_t *tx_parity,
                                        uint8_t *rx,
                                        size_t rx_len,
                                        uint8_t *rx_parity,
                                        uint32_t *cycles);

int nfc_target_send_bytes(struct nfc_device *device, const uint8_t *tx, size_t tx_len, int timeout);

int nfc_target_receive_bytes(struct nfc_device *device, uint8_t *rx, size_t rx_len, int timeout);

int nfc_target_send_bits(struct nfc_device *device,
                         const uint8_t *tx,
                         size_t tx_bits_len,
                         const uint8_t *tx_parity);

int nfc_target_receive_bits(struct nfc_device *device,
                            uint8_t *rx,
                            size_t rx_len,
                            uint8_t *rx_parity);

int nfc_emulate_target(struct nfc_device *device, void *emulator, int timeout);

void iso14443a_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443a_crc_append(uint8_t *data, size_t len);

void iso14443b_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443b_crc_append(uint8_t *data, size_t len);

uint8_t *iso14443a_locate_historical_bytes(uint8_t *ats, size_t ats_len, size_t *tk_len);

int pn53x_transceive(struct nfc_device *device,
                     const uint8_t *tx,
                     size_t tx_len,
                     uint8_t *rx,
                     size_t rx_len,
                     int timeout);

int pn53x_read_register(struct nfc_device *device, uint16_t register_, uint8_t *value);

int pn53x_write_register(struct nfc_device *device,
                         uint16_t register_,
                         uint8_t symbol_mask,
                         uint8_t value);

int pn532_SAMConfiguration(struct nfc_device *device, int mode, int timeout);

int nfc_abort_command(struct nfc_device *device);

int nfc_idle(struct nfc_device *device);

const char *nfc_device_get_name(struct nfc_device *device);

const char *nfc_device_get_connstring(struct nfc_device *device);

int nfc_device_get_supported_modulation(struct nfc_device *device,
                                        enum nfc_mode mode,
                                        const enum nfc_modulation_type **supported);

int nfc_device_get_supported_baud_rate(struct nfc_device *device,
                                       enum nfc_modulation_type modulation_type,
                                       const enum nfc_baud_rate **supported);

int nfc_device_get_supported_baud_rate_target_mode(struct nfc_device *device,
                                                   enum nfc_modulation_type modulation_type,
                                                   const enum nfc_baud_rate **supported);

int nfc_device_get_information_about(struct nfc_device *device, char **buf);

int nfc_device_get_last_error(const struct nfc_device *device);

const char *nfc_strerror(const struct nfc_device *device);

int nfc_strerror_r(const struct nfc_device *device, char *buf, size_t buflen);

void nfc_perror(const struct nfc_device *device, const char *message);

#if !defined(RUST_TEST)
void nfc_rs_context_log_init(const struct nfc_context *context);
#endif

#if !defined(RUST_TEST)
void nfc_rs_context_log_exit(void);
#endif

extern int pn53x_init(struct nfc_device *device);

extern int pn53x_check_communication(struct nfc_device *device);

extern int pn53x_set_property_int(struct nfc_device *device, enum nfc_property property, int value);

extern int pn53x_set_property_bool(struct nfc_device *device,
                                   enum nfc_property property,
                                   bool enabled);

extern int pn53x_idle(struct nfc_device *device);

extern int pn53x_initiator_init(struct nfc_device *device);

extern int pn532_initiator_init_secure_element(struct nfc_device *device);

extern int pn53x_initiator_select_passive_target(struct nfc_device *device,
                                                 struct nfc_modulation modulation,
                                                 const uint8_t *init_data,
                                                 size_t init_data_len,
                                                 struct nfc_target *target);

extern int pn53x_initiator_poll_target(struct nfc_device *device,
                                       const struct nfc_modulation *modulations,
                                       size_t modulations_len,
                                       uint8_t poll_nr,
                                       uint8_t period,
                                       struct nfc_target *target);

extern int pn53x_initiator_select_dep_target(struct nfc_device *device,
                                             enum nfc_dep_mode mode,
                                             enum nfc_baud_rate baud_rate,
                                             const struct nfc_dep_info *initiator,
                                             struct nfc_target *target,
                                             int timeout);

extern int pn53x_initiator_transceive_bits(struct nfc_device *device,
                                           const uint8_t *tx,
                                           size_t tx_bits_len,
                                           const uint8_t *tx_parity,
                                           uint8_t *rx,
                                           uint8_t *rx_parity);

extern int pn53x_initiator_transceive_bytes(struct nfc_device *device,
                                            const uint8_t *tx,
                                            size_t tx_len,
                                            uint8_t *rx,
                                            size_t rx_len,
                                            int timeout);

extern int pn53x_initiator_transceive_bits_timed(struct nfc_device *device,
                                                 const uint8_t *tx,
                                                 size_t tx_bits_len,
                                                 const uint8_t *tx_parity,
                                                 uint8_t *rx,
                                                 uint8_t *rx_parity,
                                                 uint32_t *cycles);

extern int pn53x_initiator_transceive_bytes_timed(struct nfc_device *device,
                                                  const uint8_t *tx,
                                                  size_t tx_len,
                                                  uint8_t *rx,
                                                  size_t rx_len,
                                                  uint32_t *cycles);

extern int pn53x_initiator_deselect_target(struct nfc_device *device);

extern int pn53x_initiator_target_is_present(struct nfc_device *device,
                                             const struct nfc_target *target);

extern int pn53x_target_init(struct nfc_device *device,
                             struct nfc_target *target,
                             uint8_t *rx,
                             size_t rx_len,
                             int timeout);

extern int pn53x_target_receive_bits(struct nfc_device *device,
                                     uint8_t *rx,
                                     size_t rx_len,
                                     uint8_t *rx_parity);

extern int pn53x_target_receive_bytes(struct nfc_device *device,
                                      uint8_t *rx,
                                      size_t rx_len,
                                      int timeout);

extern int pn53x_target_send_bits(struct nfc_device *device,
                                  const uint8_t *tx,
                                  size_t tx_bits_len,
                                  const uint8_t *tx_parity);

extern int pn53x_target_send_bytes(struct nfc_device *device,
                                   const uint8_t *tx,
                                   size_t tx_len,
                                   int timeout);

extern const char *pn53x_strerror(const struct nfc_device *device);

extern int pn53x_PowerDown(struct nfc_device *device);

extern int pn53x_check_ack_frame(struct nfc_device *device,
                                 const uint8_t *rx_frame,
                                 size_t rx_frame_len);

extern int pn53x_build_frame(uint8_t *frame,
                             size_t *frame_len,
                             const uint8_t *data,
                             size_t data_len);

extern int pn53x_get_supported_modulation(struct nfc_device *device,
                                          enum nfc_mode mode,
                                          const enum nfc_modulation_type **supported_modulation_types);

extern int pn53x_get_supported_baud_rate(struct nfc_device *device,
                                         enum nfc_mode mode,
                                         enum nfc_modulation_type modulation_type,
                                         const enum nfc_baud_rate **supported_baud_rates);

extern int pn53x_get_information_about(struct nfc_device *device, char **buffer);

extern void *pn53x_data_new(struct nfc_device *device, const struct pn53x_io *io);

extern void pn53x_data_free(struct nfc_device *device);

#endif  /* LIBNFC_RS_PRIVATE_H */

/* End of generated private header */
