// This header is generated by cbindgen. Do not edit manually.
// Regenerate with: python3 rust/proximate-sys/tools/generate_cbindgen_header.py --output rust/proximate-sys/include/libnfc_rs.h

// Manually-provided macros for values that cbindgen cannot emit
#define LOG_CATEGORY "libnfc.common"
#define MALLOC_LABEL "malloc"
#define DEVICE_NAME_LENGTH 256
#define MAX_USER_DEFINED_DEVICES 4
#define NFC_BUFSIZE_CONNSTRING 1024
#define NFC_COMMON_SUCCESS 0
#define NFC_COMMON_ERROR -1
#define LOG_GROUP_GENERAL 1
#define LOG_PRIORITY_ERROR 1
#define LOG_PRIORITY_DEBUG 3
#define NFC_SECURE_SUCCESS 0
#define NFC_SECURE_ERROR_INVALID -1
#define NFC_SECURE_ERROR_OVERFLOW -2
#define NFC_SECURE_ERROR_RANGE -3
#define NFC_SECURE_ERROR_ZERO_SIZE -4
#define NFC_SECURE_ERROR_INTERNAL -5
typedef struct nfc_driver nfc_driver;


#ifndef LIBNFC_RS_H
#define LIBNFC_RS_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct nfc_user_defined_device {
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool optional;
} nfc_user_defined_device;

typedef struct nfc_context {
  bool allow_autoscan;
  bool allow_intrusive_scan;
  uint32_t log_level;
  struct nfc_user_defined_device user_defined_devices[MAX_USER_DEFINED_DEVICES];
  unsigned int user_defined_device_count;
} nfc_context;

typedef struct nfc_device {
  const struct nfc_context *context;
  const nfc_driver *driver;
  void *driver_data;
  void *chip_data;
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool bCrc;
  bool bPar;
  bool bEasyFraming;
  bool bInfiniteSelect;
  bool bAutoIso14443_4;
  uint8_t btSupportByte;
  int last_error;
} nfc_device;

int nfc_parse_connstring(const char *connstring,
                         const char *prefix,
                         const char *param_name,
                         char *param_value,
                         size_t param_value_size);

int nfc_build_connstring(char *dest,
                         size_t dest_size,
                         const char *driver_name,
                         const char *param_name,
                         const char *param_value);

void nfc_set_last_error(const char *message);

void nfc_rs_free(void *ptr);

int connstring_decode(const char *connstring,
                      const char *driver_name,
                      const char *bus_name,
                      char **pparam1,
                      char **pparam2);

struct nfc_context *nfc_context_alloc_defaults(void);

struct nfc_device *nfc_device_new(const struct nfc_context *context, const char *connstring);

void nfc_device_free(struct nfc_device *device);

int nfc_safe_memcpy(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_safe_memmove(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_secure_memset(void *ptr, int val, size_t size);

int nfc_secure_zero(void *ptr, size_t size);

size_t nfc_safe_strlen(const char *str, size_t maxlen);

int nfc_is_null_terminated(const char *buf, size_t bufsize);

void nfc_ensure_null_terminated(char *buf, size_t bufsize);

const char *nfc_get_last_error(void);

void nfc_clear_last_error(void);

const char *nfc_secure_strerror(int code);

#endif  /* LIBNFC_RS_H */

/* End of generated header */
