// This header is generated by cbindgen. Do not edit manually.
// Regenerate with: python3 rust/proximate-sys/tools/generate_cbindgen_header.py --output rust/proximate-sys/include/libnfc_rs.h

// Manually-provided macros for values that cbindgen cannot emit
#define LOG_CATEGORY "libnfc.common"
#define MALLOC_LABEL "malloc"
#define NFC_BUFSIZE_CONNSTRING 1024
#define NFC_COMMON_SUCCESS 0
#define NFC_COMMON_ERROR -1
#define LOG_GROUP_GENERAL 1
#define LOG_PRIORITY_ERROR 1
#define LOG_PRIORITY_DEBUG 3
#define NFC_SECURE_SUCCESS 0
#define NFC_SECURE_ERROR_INVALID -1
#define NFC_SECURE_ERROR_OVERFLOW -2
#define NFC_SECURE_ERROR_RANGE -3
#define NFC_SECURE_ERROR_ZERO_SIZE -4
#define NFC_SECURE_ERROR_INTERNAL -5

#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#else
#include <sys/types.h>
#endif

typedef struct nfc_driver nfc_driver;


#ifndef LIBNFC_RS_H
#define LIBNFC_RS_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define DEVICE_NAME_LENGTH 256

#define MAX_USER_DEFINED_DEVICES 4

#define NFC_DRIVER_NAME_MAX 64

typedef enum nfc_baud_rate {
  NBR_UNDEFINED = 0,
  NBR_106 = 1,
  NBR_212 = 2,
  NBR_424 = 3,
  NBR_847 = 4,
} nfc_baud_rate;

typedef enum nfc_modulation_type {
  NMT_UNDEFINED = 0,
  NMT_ISO14443A = 1,
  NMT_JEWEL = 2,
  NMT_ISO14443B = 3,
  NMT_ISO14443BI = 4,
  NMT_ISO14443B2SR = 5,
  NMT_ISO14443B2CT = 6,
  NMT_FELICA = 7,
  NMT_DEP = 8,
  NMT_BARCODE = 9,
  NMT_ISO14443BICLASS = 10,
} nfc_modulation_type;

typedef struct nfc_target nfc_target;

typedef struct nfc_user_defined_device {
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool optional;
} nfc_user_defined_device;

typedef struct nfc_context {
  bool allow_autoscan;
  bool allow_intrusive_scan;
  uint32_t log_level;
  struct nfc_user_defined_device user_defined_devices[MAX_USER_DEFINED_DEVICES];
  unsigned int user_defined_device_count;
} nfc_context;

typedef struct nfc_device {
  const struct nfc_context *context;
  const nfc_driver *driver;
  void *driver_data;
  void *chip_data;
  char name[DEVICE_NAME_LENGTH];
  char connstring[NFC_BUFSIZE_CONNSTRING];
  bool bCrc;
  bool bPar;
  bool bEasyFraming;
  bool bInfiniteSelect;
  bool bAutoIso14443_4;
  uint8_t btSupportByte;
  int last_error;
} nfc_device;

void nfc_set_last_error(const char *message);

void nfc_rs_free(void *ptr);

struct nfc_context *nfc_context_alloc_defaults(void);

struct nfc_device *nfc_device_new(const struct nfc_context *context, const char *connstring);

void nfc_device_free(struct nfc_device *device);

void nfc_close(struct nfc_device *device);

void nfc_free(void *ptr);

const char *nfc_version(void);

const char *str_nfc_baud_rate(enum nfc_baud_rate value);

const char *str_nfc_modulation_type(enum nfc_modulation_type value);

int str_nfc_target(char **buf, const struct nfc_target *target, bool verbose);

int nfc_emulate_target(struct nfc_device *device, void *emulator, int timeout);

void iso14443a_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443a_crc_append(uint8_t *data, size_t len);

void iso14443b_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443b_crc_append(uint8_t *data, size_t len);

uint8_t *iso14443a_locate_historical_bytes(uint8_t *ats, size_t ats_len, size_t *tk_len);

int pn53x_transceive(struct nfc_device *device,
                     const uint8_t *tx,
                     size_t tx_len,
                     uint8_t *rx,
                     size_t rx_len,
                     int timeout);

int pn53x_read_register(struct nfc_device *device, uint16_t register_, uint8_t *value);

int pn53x_write_register(struct nfc_device *device,
                         uint16_t register_,
                         uint8_t symbol_mask,
                         uint8_t value);

int pn532_SAMConfiguration(struct nfc_device *device, int mode, int timeout);

int nfc_safe_memcpy(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_safe_memmove(void *dst, size_t dst_size, const void *src, size_t src_size);

int nfc_secure_memset(void *ptr, int val, size_t size);

int nfc_secure_zero(void *ptr, size_t size);

size_t nfc_safe_strlen(const char *str, size_t maxlen);

int nfc_is_null_terminated(const char *buf, size_t bufsize);

void nfc_ensure_null_terminated(char *buf, size_t bufsize);

const char *nfc_get_last_error(void);

void nfc_clear_last_error(void);

const char *nfc_secure_strerror(int code);

#endif  /* LIBNFC_RS_H */

/* End of generated header */
