// This header is generated by cbindgen. Do not edit manually.
// Regenerate with: python3 rust/proximate-sys/tools/generate_cbindgen_header.py --output rust/proximate-sys/include/libnfc_rs.h

// Manually-provided macros for values that cbindgen cannot emit
#define LOG_CATEGORY "libnfc.common"
#define MALLOC_LABEL "malloc"
#define NFC_BUFSIZE_CONNSTRING 1024
#define NFC_COMMON_SUCCESS 0
#define NFC_COMMON_ERROR -1
#define LOG_GROUP_GENERAL 1
#define LOG_PRIORITY_ERROR 1
#define LOG_PRIORITY_DEBUG 3
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#else
#include <sys/types.h>

typedef struct nfc_driver nfc_driver;

typedef struct nfc_context nfc_context;

typedef struct nfc_device nfc_device;


#ifndef LIBNFC_RS_H
#define LIBNFC_RS_H

#pragma once

/* Generated with cbindgen:0.29.2 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum nfc_baud_rate {
  NBR_UNDEFINED = 0,
  NBR_106 = 1,
  NBR_212 = 2,
  NBR_424 = 3,
  NBR_847 = 4,
} nfc_baud_rate;

typedef enum nfc_modulation_type {
  NMT_UNDEFINED = 0,
  NMT_ISO14443A = 1,
  NMT_JEWEL = 2,
  NMT_ISO14443B = 3,
  NMT_ISO14443BI = 4,
  NMT_ISO14443B2SR = 5,
  NMT_ISO14443B2CT = 6,
  NMT_FELICA = 7,
  NMT_DEP = 8,
  NMT_BARCODE = 9,
  NMT_ISO14443BICLASS = 10,
} nfc_modulation_type;

typedef struct nfc_target nfc_target;

void nfc_close(nfc_device *device);

void nfc_free(void *ptr);

const char *nfc_version(void);

const char *str_nfc_baud_rate(enum nfc_baud_rate value);

const char *str_nfc_modulation_type(enum nfc_modulation_type value);

int str_nfc_target(char **buf, const struct nfc_target *target, bool verbose);

int nfc_emulate_target(nfc_device *device, void *emulator, int timeout);

void iso14443a_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443a_crc_append(uint8_t *data, size_t len);

void iso14443b_crc(uint8_t *data, size_t len, uint8_t *crc);

void iso14443b_crc_append(uint8_t *data, size_t len);

uint8_t *iso14443a_locate_historical_bytes(uint8_t *ats, size_t ats_len, size_t *tk_len);

int pn53x_transceive(nfc_device *device,
                     const uint8_t *tx,
                     size_t tx_len,
                     uint8_t *rx,
                     size_t rx_len,
                     int timeout);

int pn53x_read_register(nfc_device *device, uint16_t register_, uint8_t *value);

int pn53x_write_register(nfc_device *device,
                         uint16_t register_,
                         uint8_t symbol_mask,
                         uint8_t value);

int pn532_SAMConfiguration(nfc_device *device, int mode, int timeout);

#endif  /* LIBNFC_RS_H */

/* End of generated header */
