[package]
name = "proximate"
version = "0.2.0"
edition = "2024"
description = "High-level Rust facade for the experimental libnfc core."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "proximate"

[dependencies]
proximate-driver = { path = "../proximate-driver", default-features = false }
proximate-native = { path = "../proximate-native", default-features = false }
proximate-types = { path = "../proximate-types" }

[features]
default = [
    "driver-pn53x-usb",
    "driver-acr122-usb",
    "driver-acr122s",
    "driver-arygon",
    "driver-pn532-uart",
]
driver-pn53x-usb = ["proximate-native/driver-pn53x-usb"]
driver-acr122-usb = ["proximate-native/driver-acr122-usb"]
driver-acr122s = ["proximate-native/driver-acr122s"]
driver-arygon = ["proximate-native/driver-arygon"]
driver-pn532-uart = ["proximate-native/driver-pn532-uart"]
driver-pn532-spi = ["proximate-native/driver-pn532-spi"]
driver-pn532-i2c = ["proximate-native/driver-pn532-i2c"]
driver-pcsc = ["proximate-native/driver-pcsc"]
driver-acr122-pcsc = ["proximate-native/driver-acr122-pcsc"]
driver-pn71xx = ["proximate-native/driver-pn71xx"]
